### ISSUE TITLE
non-static assertException

### ISSUE THREAD

**Issue by schnittstabil** [VladaHejda/PhpUnitAssertException#1]
Is there a reason why `assertException` is static? As far as I can see there is no single static [PHPUnit Assertion](https://phpunit.de/manual/current/en/appendixes.assertions.html).

**Comment by VladaHejda** [comment]
Actually they are static: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert.php#L32
But still callable dynamically.

**Comment by schnittstabil** [comment]
Oh, strange – the docs suggests to call static methods as instance methods – but nevertheless I should have looked into the code first. Thank you.
